// Copyright 2026 The Lynxpo Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

#import "HostViewController.h"
#import <Lynx/LynxConfig.h>
#import <Lynx/LynxEnv.h>
#import <Lynx/LynxView.h>
#import "LynxGeneratedLibraryRegistry.h"

@interface HostViewController () <LynxViewLifecycle>
@property(nonatomic, strong) LynxView *lynxView;
@end

@implementation HostViewController

- (void)viewDidLoad {
  [super viewDidLoad];
  self.view.backgroundColor = [UIColor whiteColor];

  // Build a LynxConfig reusing the shared LynxEnv template provider, then let
  // Autolink auto-register every @lynxpo/mods-* native module
  // (LynxGeneratedLibraryRegistry is generated by use_lynx_library!).
  LynxConfig *config =
      [[LynxConfig alloc] initWithProvider:[LynxEnv sharedInstance].config.templateProvider];
  [[LynxGeneratedLibraryRegistry new] setup:config];

  LynxView *lynxView = [[LynxView alloc] initWithBuilderBlock:^(LynxViewBuilder *builder) {
    builder.config = config;
    builder.screenSize = self.view.bounds.size;
    builder.fontScale = 1.0;
    builder.enableGenericResourceFetcher = YES;
  }];
  lynxView.frame = self.view.bounds;
  lynxView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
  [self.view addSubview:lynxView];
  self.lynxView = lynxView;
  [lynxView addLifecycleClient:self];

  // Load the bundled showcase template if present; otherwise the view stays
  // blank. The build + Autolink module registration is the verification target.
  NSString *bundlePath = [[NSBundle mainBundle] pathForResource:@"host" ofType:@"lynx.bundle"];
  if (bundlePath) {
    [lynxView loadTemplateFromURL:[NSURL fileURLWithPath:bundlePath] initData:nil];
  }
  [lynxView triggerLayout];
}

@end
